l_english:
 # General 
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$ sekund"
 # Graphics
 SETTING_RENDERER:0 "Renderowanie"
 SETTING_VSYNC:0 "Synchronizacja Pionowa"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!Sprawia, że gra i monitor mają tę samą liczbę klatek na sekundę, co zmniejsza rozrywanie obrazu.\n\nWyłączenie może zwiększyć wydajność."
 SETTING_MULTI_SAMPLING:0 "Antyaliasing (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!Użycie antyaliasingu wielu próbek (MSAA) wygładzi krawędzie obrazów.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_ANTI_ALIASING:0 "Anti-Aliasing"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!Użycie antyaliasingu wygładzi krawędzie obrazów.\n\nZalecany jest format FXAA."
 OPTION_ANTI_ALIASING_DISABLED:0 "Wyłączony"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "Filtrowanie Tekstur"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Użycie filtrowania anizotropowego poprawi wygląd teksturowanych powierzchni.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_FULLSCREEN_RESOLUTION:0 "Rozdzielczość"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:2 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Ustawia jakość obrazu gry.\n\nNiższe rozdzielczości mogą zwiększyć wydajność"
 SETTING_WINDOWED_RESOLUTION:0 "Rozdzielczość w Oknie"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:0 "Rozdzielczość gry. Wyższa rozdzielczość jest bardziej wymagająca dla komputera"
 SETTING_DISPLAY:0 "Monitor"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!Jeśli twój komputer ma kilka monitorów, wybierz ten, który ma być używany przez grę."
 SETTING_GRAPHICS_DEVICE:0 "Karta Graficzna"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!Wybiera kartę graficzną, której będzie używać gra. \n\nKorzystanie ze zintegrowanej karty graficznej lub programu renderującego może zmniejszyć wydajność."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Jakość Cieni"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Określa, z jaką rozdzielczością mapy cieni są renderowane, jeśli cienie są włączone.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_DISPLAY_MODE:0 "Tryb Wyświetlania"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!Określa sposób wyświetlania gry na ekranie"
 SETTING_BLOOM:0 "Bloom"
 SETTING_MESH_LOD_BIAS:0 "Jakość Poziomu Szczegółów Siatki"
 SETTING_MESH_LOD_FADE:0 "Zanikanie Poziomu Szczegółów Siatki"
 SETTING_TERRAIN_SMOOTHING:1 "Wygładzanie Terenu"
 OPTION_FULLSCREEN:0 "Pełen Ekran"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Wyświetl grę na całym ekranie. Ustawienie rozdzielczości zmieni ostrość obrazu."
 OPTION_WINDOWED:0 "W Oknie"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Okno z ustawioną rozdzielczością z ustawieniami szerokości i wysokości w oknie."
 OPTION_DISABLED:1 "Wyłączone"
 OPTION_OFF:0 "Wyłączone"
 OPTION_LOW:0 "Niskie"
 OPTION_MEDIUM:0 "Średnie"
 OPTION_HIGH:0 "Wysokie"
 OPTION_ULTRA:1 "Ultra"
 OPTION_CUSTOM:0 "Własne"
 OPTION_DEFAULT:1 "Domyślne"
 SETTINGS_CATEGORY_UI:0 "Interfejs"
 SETTINGS_CATEGORY_GAME:0 "Gra"
 SETTING_TEXTURE_QUALITY:1 "Jakość Tekstur"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\nKontroluje rozdzielczość ładowanych tekstur.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_QUALITY:0 "Predefiniowane Ustawienia Jakości"
 SETTING_SFX:0 "Efekty Specjalne"
 SETTING_UI:0 "Interfejs"
 SETTING_MAPOBJECT_QUALITY:1 "Obiekty na Mapie"
 SETTING_REFRACTION_QUALITY:1 "Jakość Refrakcji"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!Wybierz predefiniowane ustawienie zaawansowanych opcji graficznych poniżej.\n\nUstawienie niskich ustawień predefiniowanych zwiększy wydajność." 
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!Włącza efekt "bloom", w którym bardzo jasne światła rozlewają się na inne części obrazu"
 SETTING_REFRACTION_TOOLTIP:0 "Określa, czy refrakcje pojawiają się na wodzie, czy nie."
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\nKontroluje jakość refrakcji wody, jeśli są one włączone.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nOkreśla najwyższy poziom jakości obiektów mapy (takich jak budynki).\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nOkreśla jakość LODów (poziomów szczegółowości) na obiektach mapy, takich jak modele jednostek.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!Po włączeniu modele 3D płynnie przechodzą między różnymi poziomami szczegółowości (LOD) podczas przybliżania lub oddalania.\n\nWyłączenie może zwiększyć wydajność."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Określa sposób wyświetlania nazw miast i prowincji na mapie."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Określa, czy nieprzekraczalny teren znajduje się w granicach kraju na mapie."
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nOkreśla język interfejsu użytkownika."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Twój adres e-mail konta Paradox"
 SETTING_FRAMERATE_CAP:1 "Maksymalna liczba FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nMaksymalna liczba FPS (klatek na sekundę) renderowana przez grę.\n\nNiższe ustawienia mogą zmniejszyć zużycie energii."
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 # GUI
 SETTING_ANIMATION_SPEED:0 "Prędkość Animacji"
 SETTING_GUI_SCALING:0 "Skalowanie GUI"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!Kontroluje skalę całego interfejsu użytkownika. Przydatne przy wyższych rozdzielczości ekranu.\n\n#X Ustawienie zbyt dużej wartości spowoduje, że interfejs nie będzie poprawnie pasować do ekranu!#!"
 # System
 SETTING_MOUSE_PANNING:0 "Przewijanie Krawędzi Ekranu"
 SETTING_MOUSE_PANNING_TOOLTIP:3 "#T $SETTING_MOUSE_PANNING$\n#!Określa, czy kamerę można przesuwać, przesuwając mysz do krawędzi ekranu."
 SETTING_SCROLL_SPEED:0 "Prędkość przewijania"
 SETTING_CAMERA_ROTATION_SPEED:0 "Prędkość obrotu oamery"
 SETTING_ZOOM_SPEED:0 "Prędkość przybliżania"
 SETTING_INPUT_DEVICE:0 "Urządzenie wejściowe"
 SETTING_EDITOR:0 "Edytor"
 SETTING_EDITOR_POSTFIX:0 "Edytor postxif"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Polecenie otwarcia edytora"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "Wyświetl polecenie dziennika"
 SETTING_GRACEFUL_EXIT:0 "Zgrabne wyjście"
 SETTING_LANGUAGE:0 "Język"
 MOUSE_AND_KEYBOARD:0 "Mysz i klawiatura"
 GAMEPAD:0 "Kontroler"
 SETTING_MULTISAMPLING_DISABLED:0 "Wyłączone"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Wyłączone"
 # Editor
 SETTING_CAMERA_TILT:0 "Pochylenie kamery'
 SETTING_CAMERA_STRATEGY:0 "Rodzaj kamery"
 SETTING_CENTERED_ZOOM_IN:0 "Centrowane przybliżenie"
 SETTING_CAMERA_SPEED:0 "Prędkość kamery"
 CAMERA_TABLETOP:0 "Płaska"
 CAMERA_FPS:0 "Pierwszoosobowa"
 CAMERA_WASD:0 "Styl WASD"
 # Audio
 SETTING_Music:0 "Muzyka"
 SETTING_Ambient:0 "Otoczenie"
 SETTING_Effects:0 "Efekty"
 SETTING_Master:0 "Ogólna"
 SETTING_Master_TOOLTIP:0 "#T Głośność Ogólna\n#!Kontroluje głośność wszystkich dźwięków w grze."
 SETTING_Music_TOOLTIP:0 "#T Głośność Muzyki\n#!Kontroluje głośność muzyki w tle."
 SETTING_Ambient_TOOLTIP:0 "#T Głośność Otoczenia\n#!Kontroluje głośność otoczenia."
 SETTING_SFX_TOOLTIP:0 "#T Głośność Efektów Specjalnych\n#!Kontroluje głośność efektów dźwiękowych, takich jak bitwa."
 SETTING_UI_TOOLTIP:0 "#T Głośność Interfejsu\n#!Kontroluje głośność interfejsu użytkownika."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Poziom Dziennika Debugowania"
 # Game
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!Kontroluje częstotliwość automatycznego zapisywania gry."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Określa, czy autozapis odbywa się w chmurze, czy nie."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Określa, czy kamera zawsze będzie skierowana na północ, czy nie."
 NO_AUTOSAVE:0 "Brak Autozapisu"
